package com.powerly

import android.app.Application
// Star imports bring each module's generated `module` extension (now in the module's own
// package, generated by the Koin Compiler Plugin); same-named `module` resolves by receiver.
import com.powerly.account.di.*
import com.powerly.core.data.di.*
import com.powerly.core.database.di.*
import com.powerly.core.network.di.*
import com.powerly.core.managers.di.*
import com.powerly.di.*
import com.powerly.main.di.MainModules
import com.powerly.orders.di.*
import com.powerly.payment.di.*
import com.powerly.powersource.charging.di.*
import com.powerly.powersource.details.di.*
import com.powerly.splash.di.*
import com.powerly.user.di.*
import com.powerly.vehicles.di.*
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.GlobalContext.startKoin
import org.koin.core.logger.Level
import org.koin.core.module.Module

open class App : Application() {
    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger(if (BuildConfig.DEBUG) Level.DEBUG else Level.ERROR)
            androidContext(this@App)
            // Test overrides are appended last so they win before any createdAtStart
            // singletons are eagerly instantiated.
            modules(productionModules() + testOverrideModules())
        }
    }

    private fun productionModules(): List<Module> = listOf(
        ManagersModule().module(),
        DatabaseModule().module(),
        NetworkModule().module(),
        DataModule().module(),
        PaymentModule().module(),
        OrdersModule().module(),
        AccountModule().module(),
        MainModules.homeModule,
        MainModules.ordersModule,
        MainModules.accountModule,
        MainModules.scanModule,
        VehiclesModule().module(),
        SplashModule().module(),
        UserModule().module(),
        DetailsModule().module(),
        ChargingModule().module(),
        AppModule().module(),
    )

    /** Overridden by [TestApp] to replace bindings with fakes for E2E journeys. */
    protected open fun testOverrideModules(): List<Module> = emptyList()
}


