package com.powerly.main.di

// Star imports bring each module's generated `module` extension (now in the module's own
// package, generated by the Koin Compiler Plugin); same-named `module` resolves by receiver.
import com.powerly.account.di.*
import com.powerly.home.di.*
import com.powerly.orders.di.*
import com.powerly.scan.di.*

object MainModules {
    val homeModule = HomeModule().module()
    val accountModule = AccountModule().module()
    val scanModule = ScanModule().module()
    val ordersModule = OrdersModule().module()
}